### ISSUE TITLE
IFC.js releases / monorepo?

### ISSUE THREAD

**Issue by fkleedorfer** [IFCjs/web-ifc#294]
We (the team building https://merkmalservice.at) have been using IFC.js since maybe April. Our use case seems to be a bit different from most - a crucial part of our project is manipulating and writing IFC - and this has prompted us to raise a few issues concerning this aspect of IFC.js. 

We've noticed, however, that, while issues do get fixed by the bounty hunters, new releases are rare, so we have to keep workarounds around maybe a bit longer than we would like to.

We've looked into the project and noticed as well that this might have to do with its dependency structure (e.g., web-ifc-viewer -> web-ifc-three ->  web-ifc): Managing these three packages as separate projects may make it difficult to create a consistent release.

I've recently had a quite positive experience developing [qudtlib-js](https://github.com/qudtlib/qudtlib-js) as a multi-package project with [lerna](https://lerna.js.org/).
It allows you to maintain multiple packages in subfolders of the project folder (in the form of 'workspaces' - as they are already in use in IFC.js). A package can depend on the current state of another package by using the version string `'*'`, and when the project is released, the release version is substituted. Thus, you are always ready to release. If you combine it with a github action, the work required for a release to npmjs.org might just be one click. 

Now I've tried in the past days to create such a [monorepo for IFC.js](https://github.com/Merkmalservice/ifcjs/), but I did not manage to get a complete build. Here is what I did:
* make a new repository, set it up as a lerna project
* in the `packages/` folder, add `web-ifc`, `web-ifc-three`, and `web-ifc-viewer` as submodules.
* change the package names to scoped packages (because that makes managing the artifacts on npmjs by multiple people easier). e.g. `web-ifc` ->`@ifc-js/web-ifc`
* change all the import statements to reflect the changes
* add a `'build'` script to every `package.json` so we can build them all from the top level of the project with `npx lerna run build`
* rename some packages to avoid duplication
* delete the `postinstall` script from the `web-ifc/package.json` file as it triggers an additional build that is not managed by lerna

I get `web-ifc` (actually, `@ifc-js/web-ifc`) to build, but not the other projects. I believe that they are just too different from the way lerna expects a project to work (i.e. 'well-behaved'). Some of what I see is:
- the main package is a subfolder of the project folder 
- the project is also a package 
- the project's build scripts trigger the subfolder build scripts, sometimes via the `build` target, sometimes via postinstall hooks
- some examples packages get built during a standard build
... some part of this seems to throw off lerna's dependency management. Also, it is not simple, and as such, not easy to understand and debug

To get to the point, finally: 

I believe that IFC.js could benefit from moving its code into a monorepo (at least for what I believe to be the three main projects, `web-ifc`, `web-ifc-three` and `web-ifc-viewer`), but we would have to refactor them a bit:
* all packages should be direct subfolders of the `repositories` folder
* I think the scoping all packages with , for example `ifc-js` (which I created on npmjs.org as an organization so I can test my changes and which I am more than happy to share/contribute) is a good idea.
* All the examples, viewers, etc can have their place in there, too - probably as direct child directories of the repo

In addition to that I suggest
* a github action that performs a release
* switching to one version for all packages (i.e, each package that has changes is released with the same version number - and we probably have to start with 2.0.0). This is the default in lerna, and it's nice because you don't have to wonder about questions like "which versions of the viewer requres which version of web-ifc?"
* a [changelog](https://keepachangelog.com/en/1.0.0/) at the top-level that we maintain manually (just like it's done in [qudtlib(https://github.com/qudtlib/qudtlib-js)), and that gets adapted with the release version when we release

If there is interest in pursuing this route, we (@fkleedorfer, @quasarchimaere, @maxstolze and @clemensjur) are more than happy to help.

**Comment by fkleedorfer** [comment]
I can see that this proposal would be a big step with a few disadvantages:
- The repos involved would have to be archived
- All forks would become unusable
- Ongoing work would have to be migrated to the new repo
However, the advantages, I believe, outweigh them:
- enables working on packages in parallel while using the latest code in dependent packages
- enables automated nightly pre-releases (making bug-hunting easier for people using the pre-release versions, who otherwise would have to build from source) 
- ability to release anytime 
- simpler project structure makes contributing easier

Maybe we can use advanced git sorcery to merge the relevant parts of the individual repos into the combined one, which would make it easier to pull in changes made to the original repos after the work on combining them has started. After a bit of googling I am not convinced that it is impossible. This would alleviate the third disadvantage, people could keep working on the existing code.

@tomvandig @agviegas @beachtom @QuimMoya what do you think? Should we try?

**Comment by beachtom** [comment]
I do completely accept there haven't been any new releases for a while. We have had significant problems improving the geometry and quite frankly it hasn't ready for a release.

I do agree with the points about a github actions performing releases and changelogs. These are valid and we should probably do these! We should also start using the releases features of github.

I am not convinced yet about merging the repos. There are different people working on each repo - and they can be used in isolation. i.e. if you want to do command line no processing you can just use this repo. I am happy to be convinced - but to me the problems of going mono-repo do outweigh the advantages - at least to me at the moment

**Comment by agviegas** [comment]
Hey @fkleedorfer thanks a lot for your suggestions!

We are aware of the problems you mentioned. Some of the reasons are: 

- So far it is that this project is something we have done primarily in our spare time, including the money we have raised to pay the bounty hunters.

- The project has been growing organically. We didn't know what we were going to find because we had never done anything like this before, and we have been coming up with ideas and building as we go along.

However, this year there are going to be some big changes. A company is being set up right now, and it's very likely that there will be a full-time development team dedicated to this. That means there will be more resources to make more frequent releases and be quicker to fix problems. That said, I agree with @beachtom that merging repositories would be hard, primarily for three reasons:

- The complexity of compiling web-ifc. The only way to compile web-ifc is using emscripten or docker, and there are a lot of users who don't know how to use either technology. This means that forcing them to download web-ifc would force us to put together a piecemeal compilation that would make everything much more complex.

- Code size. A lot of people just want web-ifc, and forcing them to download everything we've done seems illogical, especially assuming that this year the code size is going to multiply, with new features and tools.

- Speed of code change. Although the releases may seem few, the amount of changes that occur are enormous. The fundamental reason is that IFC.js is not trying to solve a bounded problem, so once the code is "finished", it only needs to be maintained and small bugs need to be fixed. There is a continuous research, improvement and input of new ideas to replace old ones. For example, look at web-ifc-three and web-ifc-viewer: these are technologies that work well for IFCs up to 500mb on PCs, but what about larger files or mobile devices? We are now developing BIM tiles, a new technology that is able to open them, but this is different than web-ifc-three and web-ifc-viewer, and is likely to eventually replace it, which would create big deprecation problems in that merged repository. The same would happen if tomorrow we discover another geometry api that allows us to model in 3D.

Nevertheless, I find the other ideas you have brought up interesting. In particular, the use of github actions for changelogs and the use of github's versioning functionality is something we can start doing now. I'm going to create an issue with bounty to start with.

On the other hand, we are currently creating a repository of 3D BIM tools disconnected from IFC [here](https://github.com/ifcjs/components). In this repository we are trying to propose a clearer and cleaner structure, an automatic documentation with tsdoc and an automatic testing system. Our idea is that all repositories will end up like this. If you have any other ideas to improve, we'll be super happy to hear them and discuss them. :)

**Comment by beachtom** [comment]
We will in the future when we do our releases using released on github and it is setup to push automatically to NPM. I think this is as far as we are going to take this automation at this point
