### ISSUE TITLE
Geometry: broken column geometry

### ISSUE THREAD

**Issue by andy-wrks** [IFCjs/web-ifc#340]
This issue can be reproduced on https://ifcjs.github.io/web-ifc/demo/
(I'm using this as a reference, since it seems to be the most up to date version)

The attached file has a column with some cladding in it (basically a preset in ArchiCAD 26) and was exported as a single IfcColumn entity.

Expected geometry output (BIMcollab):
![image](https://user-images.githubusercontent.com/111515188/220612885-c2334692-a064-444f-bd33-3130b7612252.png)

Current geometry output (https://ifcjs.github.io/web-ifc/demo/):
![image](https://user-images.githubusercontent.com/111515188/220613073-27b7b887-31cd-46dd-b878-1167fb217f1b.png)
![image](https://user-images.githubusercontent.com/111515188/220613277-505942d4-df85-4079-ada7-8f068ad64a99.png)

[Column.zip](https://github.com/IFCjs/web-ifc/files/10803425/Column.zip)

**Comment by QuimMoya** [comment]
Hello @andy-wrks 

The geometry itself is not broken. The problem is that the web-ifc example viewer only shows positive faces. The apparent missing faces are already here, but you can only see them from the other side.
![image](https://user-images.githubusercontent.com/12625508/222400052-05ef2f86-687a-47f6-a34e-d26bef99328a.png)
![image](https://user-images.githubusercontent.com/12625508/222400262-e5db7767-4900-4a7d-8d8d-7e8c0b9c4fe9.png)

The problem is with normals. Sometimes normals get the wrong side. I'm working on it.

**Comment by andy-wrks** [comment]
Ok, thanks for the update :-)
I guess it makes sense to only show the front side of faces in a world that (ideally) consists of closed volumes.
Much luck in finding out what's going on with the normals in this case!

**Comment by QuimMoya** [comment]
Solved!
![image](https://user-images.githubusercontent.com/12625508/222427758-94d70dee-f90f-45c4-9dc5-805e8022ae5a.png)
Just added a clockwise verification in the profile object
