### ISSUE TITLE
IFCViewer dosent display windows correctly

### ISSUE THREAD

**Issue by jstec** [IFCjs/web-ifc#383]
Displaying attached ifc model, windows doesnt display correctly, window glass is not transparent.
[Archicad-Unifamiliar.zip](https://github.com/IFCjs/web-ifc-viewer/files/11312552/Archicad-Unifamiliar.zip)

**Comment by jstec** [comment]
I can't find the issue in  IFCjs/web-ifc-viewer.
Attached file show how left and right windows are not transparent, but central windows it is.
![NonTransparentWindowGlass](https://user-images.githubusercontent.com/40486368/234206598-a0113604-bc67-4f1e-9845-bb756c5622ce.png)

**Comment by jespa007** [comment]
Hi @jestec,

I've tested that ifc in the demo pages of web-ifc-three and web-ifc-viewer and you are right, the viewer loads the model with windows without transparency. This is because the feature is not implemented int the web-ifc currently included in web-ifc-three and web-ifc-viewer. A recent version of web-ifc it shows the windows transparent,


![image](https://user-images.githubusercontent.com/7852409/234216571-1db8316a-4a91-49e9-82f4-e34f7be2e713.png)

So is a matter that web-ifc-three and web-ifc-viewer it gets updated with the last web-ifc.

**Comment by jstec** [comment]
Is online demo https://ifcjs.github.io/web-ifc-viewer/example/index already update with latest version?

**Comment by beachtom** [comment]
https://ifcjs.github.io/web-ifc/demo/ is - so if it works there then it will work in the next release
