### ISSUE TITLE
Skip IfcGrid without attribute axis name

### ISSUE THREAD

**Issue by g-rodigy** [IFCjs/web-ifc#431]
### What happened?

When I try to parse model wich has element IfcGrid without axis names, parse failing. Can I avoid this or IfcGrid always must have name?

### Version

0.0.39, 0.0.42

### Relevant log output

```shell
INFO:  Parsing Model using IFC2X3 Schema
TypeError: Cannot read properties of null (reading 'map')
    at 3009204131 (...\node_modules\web-ifc\web-ifc-api-node.js:12645:381)
    at IfcAPI2.GetLine (...\node_modules\web-ifc\web-ifc-api-node.js:63239:84)
    ...
```

### Anything else?

3009204131 (...\node_modules\web-ifc\web-ifc-api-node.js:12645:381)
is:
````ts
3009204131: (id: number, v: any[]) => new IFC2X3.IfcGrid(
	id, 
	new IFC2X3.IfcGloballyUniqueId(v[0].value), 
	new Handle < IFC2X3.IfcOwnerHistory > (v[1].value),
	!v[2] ? null : new IFC2X3.IfcLabel(v[2].value), 
	!v[3] ? null : new IFC2X3.IfcText(v[3].value), 
	!v[4] ? null : new IFC2X3.IfcLabel(v[4].value), 
	!v[5] ? null : new Handle <IFC2X3.IfcObjectPlacement> (v[5].value), 
	!v[6] ? null : new Handle <IFC2X3.IfcProductRepresentation> (v[6].value), 
	[7].map((p: any) => new Handle <IFC2X3.IfcGridAxis> (p.value)), 
	v[8].map((p: any) => new Handle <IFC2X3.IfcGridAxis> (p.value)), 
	!v[9] ? null : v[9].map((p: any) => new Handle <IFC2X3.IfcGridAxis> (p.value))
),
````

**Comment by g-rodigy** [comment]
The exported part model without axis name looks like this
![image](https://github.com/IFCjs/web-ifc/assets/30372087/1b06a1c2-bebe-4231-ac30-c45edd7681e5)

**Comment by beachtom** [comment]
Hmm no it should work - let me test it out

**Comment by beachtom** [comment]
Are you able to share the model file? Or can you show the part with the actual IFCGrid line in?

**Comment by g-rodigy** [comment]
[model.zip](https://github.com/IFCjs/web-ifc/files/11995823/model.zip)

**Comment by beachtom** [comment]
OK - so in the latest version of web-ifc this will actually give a sensible error because the IFC Grid lines in this file are actually invalid, they are missing the VAxis property which is mandatory in the IFC standard.

i.e.

INCORRECT - last but one parameter is missing - but is mandatory:

#87626= IFCGRID('1D7qIxVlz9tvebFwJ0Iwer',#5,$,$,$,#87625,#87622,(#87475,#87479,#87483,#87487,#87491,#87495,#87499,#87503,#87507,#87511,#87515,#87519,#87523,#87527,#87531,#87535,#87539,#87543,#87547,#87551,#87555,#87559,#87563,#87567,#87571,#87575,#87579,#87583,#87587,#87591,#87595,#87599,#87603,#87607,#87611,#87615,#87619),$,$);

Corrected - by adding a VAxis propery:

#87626= IFCGRID('1D7qIxVlz9tvebFwJ0Iwer',#5,$,$,$,#87625,#87622,(#87475,#87479,#87483,#87487,#87491,#87495,#87499,#87503,#87507,#87511,#87515,#87519,#87523,#87527,#87531,#87535,#87539,#87543,#87547,#87551,#87555,#87559,#87563,#87567,#87571,#87575,#87579,#87583,#87587,#87591,#87595,#87599,#87603,#87607,#87611,#87615,#87619),(#87619),$);
